# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f9c773b3662fbe5c74ca5210032334df5cf8f5a027a1c2dccf1de55dc09238bc1b0790bc3edc790cb3df1c3b4f2ea78616d553a52d25bb79ee89dff560096b1

test:
  secret_key_base: ddaf1f6af1a132c911a07817af346dbf96c801d3256b841fdffe0b25d7b0757c749cd3a828f1c00fc3b9a78d1e1b5ddf6701cc469ad2680bb4b3bc74aa909903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
